application: ks-home-test
version: stage
runtime: python27
api_version: 1
threadsafe: yes

pagespeed:
  enabled_rewriters:
  - RemoveComments
  - CollapseWhitespace
  - MinifyCss
  - CombineJs
  - CombineCss
  - InlineCss
  - CombineHeads
  - InlineImages
  - DeferJs
  - WebpOptimization
  - MoveCssToHead

  disabled_rewriters:
  - FlushSubresources

handlers:

- url: /api-email/.*
  script: api-email.application

- url: /(.+)
  static_files: public/\1
  upload: public/(.*)

- url: /
  static_files: public/index.html
  upload: public/index.html



skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
- ^posts/(.*/)?
- ^src/(.*/)?
- ^samples/(.*/)?
